In [4]:
import numpy as np
import pandas as pd

In [80]:
from google.colab import files

uploaded = files.upload()

Saving sales_practice.csv to sales_practice (1).csv

In [81]:
df =pd.read_csv('sales_practice.csv')
df

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating
0,1001,2025-07-13,Customer_131,50.0,Mumbai,Electronics,5184.0,5.0,0.0,Card,4.0
1,1002,2025-04-06,Customer_10,22.0,Chandigarh,Books,621.0,4.0,15.0,NetBanking,5.0
2,1003,2025-03-25,Customer_60,53.0,Bengaluru,Books,870.0,3.0,5.0,UPI,4.0
3,1004,2025-04-28,Customer_69,23.0,Bengaluru,Grocery,1307.0,5.0,5.0,Card,4.0
4,1005,2025-08-07,Customer_119,20.0,Chandigarh,Grocery,447.0,1.0,0.0,NetBanking,5.0
...,...,...,...,...,...,...,...,...,...,...,...
503,1068,2025-08-09,Customer_136,47.0,Chandigarh,Clothing,1222.0,4.0,0.0,Card,5.0
504,1480,2025-10-17,Customer_21,40.0,Mumbai,Electronics,17841.0,3.0,0.0,Cash,5.0
505,1486,2025-10-17,Customer_54,48.0,Amritsar,Clothing,2714.0,5.0,5.0,Card,4.0
506,1311,2025-03-31,Customer_42,42.0,Delhi,Books,135.0,3.0,5.0,Cash,4.0
507,1032,2025-01-04,Customer_27,55.0,Jalandhar,Clothing,912.0,1.0,0.0,Cash,3.0

# **Pandas**

# let's see first five rows

In [82]:
df.head()

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating
0,1001,2025-07-13,Customer_131,50.0,Mumbai,Electronics,5184.0,5.0,0.0,Card,4.0
1,1002,2025-04-06,Customer_10,22.0,Chandigarh,Books,621.0,4.0,15.0,NetBanking,5.0
2,1003,2025-03-25,Customer_60,53.0,Bengaluru,Books,870.0,3.0,5.0,UPI,4.0
3,1004,2025-04-28,Customer_69,23.0,Bengaluru,Grocery,1307.0,5.0,5.0,Card,4.0
4,1005,2025-08-07,Customer_119,20.0,Chandigarh,Grocery,447.0,1.0,0.0,NetBanking,5.0

# see last rows

In [83]:
df.tail()

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating
503,1068,2025-08-09,Customer_136,47.0,Chandigarh,Clothing,1222.0,4.0,0.0,Card,5.0
504,1480,2025-10-17,Customer_21,40.0,Mumbai,Electronics,17841.0,3.0,0.0,Cash,5.0
505,1486,2025-10-17,Customer_54,48.0,Amritsar,Clothing,2714.0,5.0,5.0,Card,4.0
506,1311,2025-03-31,Customer_42,42.0,Delhi,Books,135.0,3.0,5.0,Cash,4.0
507,1032,2025-01-04,Customer_27,55.0,Jalandhar,Clothing,912.0,1.0,0.0,Cash,3.0

# sample data

In [84]:
df.sample(10)

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating
169,1170,2025-09-22,Customer_146,63.0,Delhi,Electronics,5698.0,5.0,5.0,Cash,NaN
354,1355,2025-02-08,Customer_47,52.0,Bengaluru,Sports,2587.0,2.0,10.0,Card,1.0
272,1273,2025-05-13,Customer_45,27.0,chandigarh,Electronics,2136.0,5.0,10.0,NetBanking,4.0
89,1090,2025-01-11,Customer_3,34.0,Patiala,Sports,6811.0,1.0,20.0,NetBanking,2.0
334,1335,2025-05-30,Customer_83,36.0,Amritsar,Grocery,-1.0,3.0,0.0,NetBanking,1.0
378,1379,2025-09-23,Customer_148,58.0,Mumbai,Clothing,2328.0,3.0,0.0,UPI,NaN
462,1463,2025-02-22,Customer_71,63.0,Mumbai,Books,772.0,1.0,15.0,Cash,3.0
213,1214,2025-09-25,Customer_18,42.0,Bengaluru,Grocery,1157.0,5.0,5.0,Cash,4.0
310,1311,2025-03-31,Customer_42,42.0,Delhi,Books,135.0,3.0,5.0,Cash,4.0
453,1454,2025-06-19,Customer_71,38.0,Jalandhar,Electronics,13981.0,2.0,10.0,Cash,5.0

# null or na values

In [24]:
df.isna().sum()

order_id           0
order_date         0
customer_name      0
age               20
city              10
category           0
unit_price         0
quantity           8
discount_pct       0
payment_method     0
rating            35
dtype: int64

# numeric columns ka statistical summary

In [85]:
df.describe()

,order_id,age,unit_price,quantity,discount_pct,rating
count,508.000000,488.000000,508.000000,500.00000,508.000000,473.000000
mean,1250.631890,41.803279,4793.844488,3.04400,9.950787,3.803383
std,145.013243,13.811961,7146.016619,1.40071,7.088309,1.130017
min,1001.000000,18.000000,-1.000000,1.00000,0.000000,1.000000
25%,1124.750000,29.750000,652.000000,2.00000,5.000000,3.000000
50%,1251.500000,42.000000,1392.500000,3.00000,10.000000,4.000000
75%,1375.250000,55.000000,5148.750000,4.00000,15.000000,5.000000
max,1500.000000,64.000000,29916.000000,5.00000,20.000000,5.000000

# infomation of data

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        508 non-null    int64
 1   order_date      508 non-null    object
 2   customer_name   508 non-null    object
 3   age             488 non-null    float64
 4   city            498 non-null    object
 5   category        508 non-null    object
 6   unit_price      508 non-null    float64
 7   quantity        500 non-null    float64
 8   discount_pct    508 non-null    float64
 9   payment_method  508 non-null    object
 10  rating          473 non-null    float64
dtypes: float64(5), int64(1), object(5)
memory usage: 43.8+ KB

# there are -ve values in unit_price and some columns have null value let's clean or fill them

# fill age column with avg value

In [90]:
df['age'].sample(10)

471    20.0
31     55.0
146    44.0
446     NaN
305    63.0
398    55.0
444    56.0
63     37.0
324    47.0
116    64.0
Name: age, dtype: float64

In [91]:
df['age'] = df['age'].fillna(df['age'].mean())

# changing type to int

df['age'] = df['age'].astype(int)

In [93]:
df['age'].sample(10)

98     63
133    44
449    42
491    47
475    40
474    18
388    24
301    38
119    62
96     41
Name: age, dtype: int64

In [99]:
df['age'].isna().sum()

np.int64(0)

# fill rating with mean value

In [95]:
df['rating'].sample(10)

124    4.0
246    4.0
121    3.0
51     5.0
238    2.0
94     5.0
392    4.0
166    3.0
372    3.0
103    NaN
Name: rating, dtype: float64

In [100]:
df['rating'] = df['rating'].fillna(df['rating'].mean())

In [101]:
df['rating'].sample(10)

445    3.0
193    4.0
140    3.8
340    5.0
473    4.0
480    1.0
225    2.0
30     4.0
198    4.0
92     5.0
Name: rating, dtype: float64

In [102]:
df['rating'].isna().sum()

np.int64(0)

# fill quantity with mode value

In [103]:
df['quantity'].isna().sum()

np.int64(8)

8 missing values

In [104]:
df["quantity"] = df["quantity"].fillna(df["quantity"].mode()[0]).round(2)

In [105]:
df['quantity'].head()

0    5.0
1    4.0
2    3.0
3    5.0
4    1.0
Name: quantity, dtype: float64

In [106]:
df['quantity'].isna().sum()

np.int64(0)

In [107]:
df.isna().sum()

order_id           0
order_date         0
customer_name      0
age                0
city              10
category           0
unit_price         0
quantity           0
discount_pct       0
payment_method     0
rating             0
dtype: int64

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        508 non-null    int64
 1   order_date      508 non-null    object
 2   customer_name   508 non-null    object
 3   age             508 non-null    int64
 4   city            498 non-null    object
 5   category        508 non-null    object
 6   unit_price      508 non-null    float64
 7   quantity        508 non-null    float64
 8   discount_pct    508 non-null    float64
 9   payment_method  508 non-null    object
 10  rating          508 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 43.8+ KB

# now deal with city missing values we will fill as unknown

In [109]:
df['city'] = df['city'].fillna('unknown')

In [110]:
df['city'].head()

0        Mumbai
1    Chandigarh
2     Bengaluru
3     Bengaluru
4    Chandigarh
Name: city, dtype: object

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        508 non-null    int64
 1   order_date      508 non-null    object
 2   customer_name   508 non-null    object
 3   age             508 non-null    int64
 4   city            508 non-null    object
 5   category        508 non-null    object
 6   unit_price      508 non-null    float64
 7   quantity        508 non-null    float64
 8   discount_pct    508 non-null    float64
 9   payment_method  508 non-null    object
 10  rating          508 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 43.8+ KB

# let's deal with -ve value in unit_price

In [113]:
df[df["unit_price"] < 0]
(df["unit_price"] < 0).sum()

np.int64(5)

# 5 -ve value we will drop them

In [114]:
df = df[df["unit_price"] > 0]

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 503 entries, 0 to 507
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        503 non-null    int64
 1   order_date      503 non-null    object
 2   customer_name   503 non-null    object
 3   age             503 non-null    int64
 4   city            503 non-null    object
 5   category        503 non-null    object
 6   unit_price      503 non-null    float64
 7   quantity        503 non-null    float64
 8   discount_pct    503 non-null    float64
 9   payment_method  503 non-null    object
 10  rating          503 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 47.2+ KB

In [116]:
df.describe()

,order_id,age,unit_price,quantity,discount_pct,rating
count,503.000000,503.000000,503.000000,503.000000,503.000000,503.000000
mean,1250.252485,41.827038,4841.506958,3.041750,10.009940,3.807157
std,145.024238,13.522296,7165.396636,1.387281,7.081617,1.086584
min,1001.000000,18.000000,67.000000,1.000000,0.000000,1.000000
25%,1124.500000,31.000000,669.000000,2.000000,5.000000,3.000000
50%,1250.000000,41.000000,1419.000000,3.000000,10.000000,4.000000
75%,1375.500000,54.000000,5262.000000,4.000000,15.000000,5.000000
max,1500.000000,64.000000,29916.000000,5.000000,20.000000,5.000000

# let's see we have any duplicate value in dataframe

In [121]:
df.duplicated(keep=False).sum()

np.int64(16)

In [123]:
df[df.duplicated(keep=False)].sort_values("order_id")

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating
31,1032,2025-01-04,Customer_27,55,Jalandhar,Clothing,912.0,1.0,0.0,Cash,3.0
507,1032,2025-01-04,Customer_27,55,Jalandhar,Clothing,912.0,1.0,0.0,Cash,3.0
502,1048,2025-11-07,Customer_80,45,Mumbai,Sports,4892.0,4.0,20.0,UPI,1.0
47,1048,2025-11-07,Customer_80,45,Mumbai,Sports,4892.0,4.0,20.0,UPI,1.0
67,1068,2025-08-09,Customer_136,47,Chandigarh,Clothing,1222.0,4.0,0.0,Card,5.0
503,1068,2025-08-09,Customer_136,47,Chandigarh,Clothing,1222.0,4.0,0.0,Card,5.0
500,1305,2025-02-16,Customer_137,26,Amritsar,Grocery,1120.0,4.0,0.0,Cash,3.0
304,1305,2025-02-16,Customer_137,26,Amritsar,Grocery,1120.0,4.0,0.0,Cash,3.0
506,1311,2025-03-31,Customer_42,42,Delhi,Books,135.0,3.0,5.0,Cash,4.0
310,1311,2025-03-31,Customer_42,42,Delhi,Books,135.0,3.0,5.0,Cash,4.0
340,1341,2025-06-05,Customer_64,38,Delhi,Books,331.0,3.0,20.0,UPI,5.0
501,1341,2025-06-05,Customer_64,38,Delhi,Books,331.0,3.0,20.0,UPI,5.0
504,1480,2025-10-17,Customer_21,40,Mumbai,Electronics,17841.0,3.0,0.0,Cash,5.0
479,1480,2025-10-17,Customer_21,40,Mumbai,Electronics,17841.0,3.0,0.0,Cash,5.0
485,1486,2025-10-17,Customer_54,48,Amritsar,Clothing,2714.0,5.0,5.0,Card,4.0
505,1486,2025-10-17,Customer_54,48,Amritsar,Clothing,2714.0,5.0,5.0,Card,4.0

there are 8 dupicate values let's drop them

In [124]:
df = df.drop_duplicates()

In [125]:
df[df.duplicated(keep=False)].sort_values("order_id")

Empty DataFrame
Columns: [order_id, order_date, customer_name, age, city, category, unit_price, quantity, discount_pct, payment_method, rating]
Index: []

In [126]:
df

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating
0,1001,2025-07-13,Customer_131,50,Mumbai,Electronics,5184.0,5.0,0.0,Card,4.0
1,1002,2025-04-06,Customer_10,22,Chandigarh,Books,621.0,4.0,15.0,NetBanking,5.0
2,1003,2025-03-25,Customer_60,53,Bengaluru,Books,870.0,3.0,5.0,UPI,4.0
3,1004,2025-04-28,Customer_69,23,Bengaluru,Grocery,1307.0,5.0,5.0,Card,4.0
4,1005,2025-08-07,Customer_119,20,Chandigarh,Grocery,447.0,1.0,0.0,NetBanking,5.0
...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2025-01-01,Customer_31,47,Delhi,Grocery,957.0,3.0,5.0,Cash,5.0
496,1497,2025-07-21,Customer_120,32,Amritsar,Electronics,16738.0,3.0,0.0,Card,3.0
497,1498,2025-12-29,Customer_133,34,Patiala,Clothing,1634.0,4.0,20.0,Card,3.0
498,1499,2025-04-13,Customer_5,38,Amritsar,Sports,7709.0,3.0,15.0,UPI,4.0
499,1500,2025-04-13,Customer_139,49,Patiala,Grocery,793.0,5.0,10.0,Card,1.0

In [127]:
df["city"].value_counts()

city
Ludhiana      78
Mumbai        70
Patiala       63
Jalandhar     57
Bengaluru     54
Chandigarh    54
Delhi         49
Amritsar      45
unknown       10
chandigarh     5
delhi          3
mumbai         2
ludhiana       2
jalandhar      1
patiala        1
bengaluru      1
Name: count, dtype: int64

2 delhi we have to do captilize first word

In [128]:
df["city"] = df["city"].str.title()

In [129]:
df["city"].value_counts()

city
Ludhiana      80
Mumbai        72
Patiala       64
Chandigarh    59
Jalandhar     58
Bengaluru     55
Delhi         52
Amritsar      45
Unknown       10
Name: count, dtype: int64

# let"s create a total_price column

In [130]:
df["total_price"] = (df["unit_price"] * df["quantity"] * (1 - df["discount_pct"] / 100)).round(2)

In [131]:
df.head()

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating,total_price
0,1001,2025-07-13,Customer_131,50,Mumbai,Electronics,5184.0,5.0,0.0,Card,4.0,25920.00
1,1002,2025-04-06,Customer_10,22,Chandigarh,Books,621.0,4.0,15.0,NetBanking,5.0,2111.40
2,1003,2025-03-25,Customer_60,53,Bengaluru,Books,870.0,3.0,5.0,UPI,4.0,2479.50
3,1004,2025-04-28,Customer_69,23,Bengaluru,Grocery,1307.0,5.0,5.0,Card,4.0,6208.25
4,1005,2025-08-07,Customer_119,20,Chandigarh,Grocery,447.0,1.0,0.0,NetBanking,5.0,447.00

# category-wise revenue aur city-wise average rating nikalo

In [134]:
category_revenue = df.groupby("category")["total_price"].sum()

city_avg_rating = df.groupby("city")["rating"].mean().round(2)

print(category_revenue)
print(city_avg_rating)

category
Books           130662.05
Clothing        520819.15
Electronics    5042621.55
Grocery         218060.90
Sports         1016052.90
Name: total_price, dtype: float64
city
Amritsar      3.75
Bengaluru     3.88
Chandigarh    3.73
Delhi         3.69
Jalandhar     3.89
Ludhiana      3.99
Mumbai        3.84
Patiala       3.64
Unknown       3.60
Name: rating, dtype: float64

# month-wise sales nikalo

# first to change datatype then extract moth form it

In [136]:
df["order_date"].dtype

dtype('O')

In [137]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [138]:
df["order_date"].dtype

dtype('<M8[ns]')

In [139]:
df['order_date'].head()

0   2025-07-13
1   2025-04-06
2   2025-03-25
3   2025-04-28
4   2025-08-07
Name: order_date, dtype: datetime64[ns]

# extract month from date

In [148]:
df['order_month']=df['order_date'].dt.month
df['order_month_name'] = df['order_date'].dt.month_name()

In [149]:
df

,order_id,order_date,customer_name,age,city,category,unit_price,quantity,discount_pct,payment_method,rating,total_price,order_month,order_month_name
0,1001,2025-07-13,Customer_131,50,Mumbai,Electronics,5184.0,5.0,0.0,Card,4.0,25920.00,7,July
1,1002,2025-04-06,Customer_10,22,Chandigarh,Books,621.0,4.0,15.0,NetBanking,5.0,2111.40,4,April
2,1003,2025-03-25,Customer_60,53,Bengaluru,Books,870.0,3.0,5.0,UPI,4.0,2479.50,3,March
3,1004,2025-04-28,Customer_69,23,Bengaluru,Grocery,1307.0,5.0,5.0,Card,4.0,6208.25,4,April
4,1005,2025-08-07,Customer_119,20,Chandigarh,Grocery,447.0,1.0,0.0,NetBanking,5.0,447.00,8,August
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2025-01-01,Customer_31,47,Delhi,Grocery,957.0,3.0,5.0,Cash,5.0,2727.45,1,January
496,1497,2025-07-21,Customer_120,32,Amritsar,Electronics,16738.0,3.0,0.0,Card,3.0,50214.00,7,July
497,1498,2025-12-29,Customer_133,34,Patiala,Clothing,1634.0,4.0,20.0,Card,3.0,5228.80,12,December
498,1499,2025-04-13,Customer_5,38,Amritsar,Sports,7709.0,3.0,15.0,UPI,4.0,19657.95,4,April
499,1500,2025-04-13,Customer_139,49,Patiala,Grocery,793.0,5.0,10.0,Card,1.0,3568.50,4,April

# month-wise sales nikalo

In [151]:
df.groupby("order_month")["total_price"].sum()

order_month
1     361973.55
2     677858.70
3     600426.45
4     291405.40
5     608335.35
6     517837.65
7     648840.30
8     394439.40
9     673570.30
10    837015.75
11    735021.45
12    581492.25
Name: total_price, dtype: float64

In [152]:
months = [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
]

df["order_month_name"] = pd.Categorical(
    df["order_month_name"],
    categories=months,
    ordered=True
)

df.groupby("order_month_name", observed=True)["total_price"].sum()

order_month_name
January      361973.55
February     677858.70
March        600426.45
April        291405.40
May          608335.35
June         517837.65
July         648840.30
August       394439.40
September    673570.30
October      837015.75
November     735021.45
December     581492.25
Name: total_price, dtype: float64

# Top 10 customers by spending

In [154]:
top_10 = (
    df.groupby("order_id")["total_price"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_10

order_id
1465    142875.00
1426    128196.00
1310    127143.00
1233    125122.50
1280    116163.00
1171    114680.00
1443    110336.00
1150    109475.75
1414    105984.00
1045    101068.00
Name: total_price, dtype: float64

# payment_method ka value_counts()

In [155]:
df['payment_method'].value_counts()

payment_method
Card          159
NetBanking    116
UPI           116
Cash          104
Name: count, dtype: int64

# pivot_table: rows = city, columns = category, values = total

In [156]:
pivot = pd.pivot_table(
    df,
    index="city",
    columns="category",
    values="total_price",
    aggfunc="sum"
)

pivot

category       Books  Clothing  Electronics   Grocery     Sports
city
Amritsar    13441.35  78821.95    436760.15  15457.75   66918.10
Bengaluru    7723.75  50019.55    669299.40  43403.75  112553.85
Chandigarh  15070.35  41807.40    559821.65  26247.20  119927.30
Delhi       14926.40  18080.50    573294.90  23863.65  133720.45
Jalandhar   25229.50  64567.05    478521.90  23815.15   56724.15
Ludhiana    17171.80  87955.75    791569.75  38099.70  172961.80
Mumbai      18199.65  91437.65    666960.80  24634.40  180447.30
Patiala     15178.05  83731.30    786776.95  19984.90  152108.95
Unknown      3721.20   4398.00     79616.05   2554.40   20691.00

# **numpy**

# np.mean, np.median, np.std of unit_Price

## first convert to numpy arr

In [159]:
arr = df["unit_price"].to_numpy()
print(arr)

[ 5184.   621.   870.  1307.   447.  3849. 16868.   298.  1294.  8626.
  1492.  6069.   772.   753.   867.   184.  1328.  3863.  4013.   911.
   568.   840.  7384.  6667.   354.   348.  1493.  1377.  1385.   917.
   912.  6364.   462.  4788.  6301.  3863.  1277.  2299.   116. 21853.
   144.   255.   946. 25267.   805.   672.  4892.   512.   644.   742.
 13021.  3364.   511.  1477. 16126.  1117. 26500.   734.   780.  4477.
   134.  2124.  1779.  1339.  1175.  2133.  1222. 19991.   878.   859.
 13655.   459.  3379.   105.   591.  3725.  2237.  1345.   181.  1109.
  1258.  4988.   794.   423.   839. 21302.   666.   769.  6811.  1211.
  7260.  2223.  3924.  2837.  3267.  2443.   723.   602. 19989.  5083.
 23811.  6016.  5767.   760.   528.   358.   511.  1452.   786.  3384.
   470.  1186.   608.  1044.   977.  8994.  9460.   526.  5913.   678.
   482.   232.   654.  4991.   387. 11470.   394.   782.   393.  1118.
   524. 14149.   600.   246.  2837.   288. 10312.  3233.  1425.  5498.
  3690.  3460.   747.  6254.  2895. 14893.  2281.  7699. 25759.  4118.
  2714.  1937.  3276.   851.   526. 23455.   967.   155.   330.  1743.
   687.   100.   343.   916.  5680.  2162. 26100.  3700.  5698. 28670.
 19202.   608.   176.   597.  1102.   564.  4365.  4376.  1407.  5897.
  5847.  1441.   867.   295.  1211. 13388.  2496.  1947.  3195.   897.
   736.   845.  3800.  1084.  9094.  2970. 18522.   485.  1122.  2226.
  5082.   293.   237.   237.  2390.   106.  4750.  2060.   472.  2813.
   518.   682.  1157.   836.  3257. 16495. 15780.   391.  4956.  5895.
  1400.   776.   743.   728.   733.  5881.   177.   757. 20420.  1106.
  3581. 27805.   719.   351.   636.   684.   533.  3031.   818. 24879.
  1155. 19765.   316.   736. 12197.   525.   505.   350.  6413. 28916.
   264.  4415.  3763.   544. 14261.   689. 12732.  5581.  1108.   240.
 17483.  3811.  7514.  3141.  1181.   938.  2073.   211.   595.  2712.
 29625.  2136.  5854.  1277.  1429.   664.   194.  9587. 25814.  3548.
   973.   198.   226.   743.  4870.  2906.  1044.   839.    67.  1127.
  1980.  5891.  3353.   675.   478.  7759.   714.  1466. 14384.   344.
  2694. 16435.  1120. 23876.  2316.   210.  1746. 29916.   135.   803.
 21165.  1350.  3178.   769.   134.   185.  5459.   899.   388. 20639.
   209.  5340.  5137.   634.  2818. 27116. 26176.    92.   406.  1191.
  1977.  1486.  6303.  6543.   353.  7320.   331.  2728.   827.   102.
   441.   320.  1588.   792. 24959. 18965.  1471. 24441.  3863.   395.
  2587.  6855.  8856.   834. 20735.   740.  7758.  7451.   744.  6268.
 25691.  1062.  1238.  3400. 14503.   132.  1987.   261.   214.   762.
  5700. 16126.   531.   696.  2328.  2631.  4408.  6868.  3810.   874.
 24773. 22569.  3484.  1867.   519.  9581.   179. 21877.  2233.  1471.
   699.  5047. 16260.  3526.   559.  2580.   433.   133.  1110.  7119.
   715.  1078.   646.  6847.  3220.  4568. 23567.   979.  1692. 29440.
 18574.   466.  4526. 23954.  1241.   972.  7032.   557.   457.   260.
   410. 28488.  4513.  2690. 13714.   562. 17051.   659.  2356. 20178.
   691. 28336.   278.  1528. 14926.  5650.  1794. 27584.   737.   237.
   195.  3901.  1419.  1424.  1328.  1109.  2715.   941. 13981.  1189.
   935. 13221.   607.  7783. 13530.   222. 13445.   772.   365. 28575.
  4871. 18844.   509. 27772.   674.   338.  3579.   742.   737.   218.
   280.  1123. 18028.   380. 17841.  2481.  5735.  2324.   618.   901.
  2714.  2581.   508.   297.   729.  3004.  4573.   257.   445.  2259.
   957. 16738.  1634.  7709.   793.]

#  np.median, np.std,np.mean

In [165]:
print(f'mean of unit_price = {np.mean(arr).round(2)}')
print(f'meadian of unit_price = {np.median(arr)}')
print(f'std of unit_price = {np.std(arr).round(2)}')

mean of unit_price = 4860.83
meadian of unit_price = 1424.0
std of unit_price = 7179.59

# percentile vaule 25, 75

In [166]:
arr = np.sort(arr)
print(f'25th percentile of unit_price = {np.percentile(arr, 25)}')
print(f'75th percentile of unit_price = {np.percentile(arr, 75)}')

25th percentile of unit_price = 669.0
75th percentile of unit_price = 5399.5

# creating price lable column

In [167]:
df["price_label"] = np.where(df["unit_price"] > 5000, "High", "Low")

In [170]:
df[["unit_price","price_label"]].sample(10)

     unit_price price_label
449      1328.0         Low
120       678.0         Low
183       867.0         Low
475       280.0         Low
446      3901.0         Low
225       733.0         Low
456     13221.0        High
238      3031.0         Low
37       1277.0         Low
352      3863.0         Low

# price aur quantity ka correlation nikalo

In [171]:


price = df["unit_price"].to_numpy()
qty = df["quantity"].to_numpy()

corr = np.corrcoef(price, qty)
print(corr)

[[1.         0.08764787]
 [0.08764787 1.        ]]